BugMania/Controllers/BugReport/AddSubscriptionBugReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugMania.Entities;
using Microsoft.AspNet.Identity;

namespace BugMania.Controllers.BugReport
{
    [RoutePrefix("Report/Subscribe")]
    public class AddSubscriptionBugReportController : Controller
    {
        BugReportEntity bugReportEntity = new BugReportEntity();
        ApplicationUserEntity userEntity = new ApplicationUserEntity();

        // GET: /Report/
        [Route("Add")]
        public ActionResult AddSubscription(int id)
        {
            bugReportEntity.AddSubscriber(id, User.Identity.GetUserId());

            return Redirect("/Report/Details/" + id);
        }
    }
}

BugMania/Controllers/BugReport/CreateBugReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.BugReport
{
    [RoutePrefix("Report")]
    [Authorize]
    public class CreateBugReportController : Controller
    {
        private BugReportEntity bugReportEntity = new BugReportEntity();
        private PriorityEntity priorityEntity = new PriorityEntity();
        private SeverityEntity severityEntity = new SeverityEntity();
        private ProductEntity productEntity = new ProductEntity();
        private StatusEntity statusEntity = new StatusEntity();
        private TagEntity tagEntity = new TagEntity();


        // GET: Report/Create
        [Route("Create")]
        public ActionResult CreateReport()
        {
            CreateBugReportViewModel model = new CreateBugReportViewModel();

            ViewBag.PriorityId = new SelectList(priorityEntity.GetAllPriorities(), "Id", "Name");
            ViewBag.SeverityId = new SelectList(severityEntity.GetAllSeverities(), "Id", "Name");
            ViewBag.ProductId = new SelectList(productEntity.GetAllProducts(), "Id", "Name");
            ViewBag.Tags = new SelectList(tagEntity.GetAllTags(), "Id", "Name");
            return View("/Views/BugReport/CreateBugReportUI.cshtml", model);
        }

        // POST: BugReport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateReport(CreateBugReportViewModel createBugReportViewModel)
        {
            if (ModelState.IsValid)
            {
                bugReportEntity.AddBugReport(createBugReportViewModel);

                return RedirectToAction("ViewAllReports", "ViewAllBugReport");
            }

            ViewBag.PriorityId = new SelectList(priorityEntity.GetAllPriorities(), "Id", "Name", createBugReportViewModel.PriorityId);
            ViewBag.SeverityId = new SelectList(severityEntity.GetAllSeverities(), "Id", "Name", createBugReportViewModel.ProductId);
            ViewBag.ProductId = new SelectList(productEntity.GetAllProducts(), "Id", "Name", createBugReportViewModel.SeverityId);
            ViewBag.Tags = new SelectList(tagEntity.GetAllTags(), "Id", "Name");

            return View("/Views/BugReport/CreateBugReportUI.cshtml",createBugReportViewModel);
        }

        [HttpPost]
        public ActionResult GetAllTags(string value)
        {
            var tags = new SelectList(tagEntity.GetAllTags(), "Id", "Name").ToList();
            
            return Json(tags, JsonRequestBehavior.AllowGet);
        }
    }
}

BugMania/Controllers/BugReport/DeleteBugReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.BugReport
{
    [RoutePrefix("Report")]
    [Authorize(Roles = "Admin, Triager")]
    public class DeleteBugReportController : Controller
    {
        private BugReportEntity bugReportEntity = new BugReportEntity();

        // GET: BugReport/Delete/5
        [Route("Delete/{id}")]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BugMania.Shapes.BugReport bugReport = bugReportEntity.GetSingleBugReport(id);
            if (bugReport == null)
            {
                return HttpNotFound();
            }
            return View("/Views/BugReport/DeleteBugReportUI.cshtml",bugReport);
        }

        // POST: BugReport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            bugReportEntity.DeleteBugReport(id);
            return RedirectToAction("ViewAllReports", "ViewAllBugReport");
        }
    }
}

BugMania/Controllers/BugReport/EditBugReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;
using BugMania.Hubs;

namespace BugMania.Controllers.BugReport
{
    [RoutePrefix("Report")]
    [Authorize]
    public class EditBugReportController : Controller
    {
        private BugReportEntity bugReportEntity = new BugReportEntity();
        private PriorityEntity priorityEntity = new PriorityEntity();
        private SeverityEntity severityEntity = new SeverityEntity();
        private ProductEntity productEntity = new ProductEntity();
        private StatusEntity statusEntity = new StatusEntity();
        private TagEntity tagEntity = new TagEntity();

        // GET: BugReport/Edit/5
        [Route("Edit/{id}")]
        public ActionResult EditReport(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BugMania.Shapes.BugReport bugReport = bugReportEntity.GetSingleBugReport(id);
            if (bugReport == null)
            {
                return HttpNotFound();
            }

            var products = productEntity.GetAllProducts();
            var severity = severityEntity.GetAllSeverities();
            var priority = priorityEntity.GetAllPriorities();
            SelectList ProductList;
            SelectList SeverityList;
            SelectList PriorityList;

            if (User.IsInRole("Admin"))
            {
                ProductList = new SelectList(products, "Id", "Name", bugReport.ProductId);
                SeverityList = new SelectList(severity, "Id", "Name", bugReport.SeverityId);
                PriorityList = new SelectList(priority, "Id", "Name", bugReport.PriorityId);
            }
            else
            {
                // Disable editing
                ProductList = new SelectList(products, "Id", "Name", bugReport.ProductId, products.Select(t => t.Id));
                SeverityList = new SelectList(severity, "Id", "Name", bugReport.SeverityId, severity.Select(t => t.Id));
                PriorityList = new SelectList(priority, "Id", "Name", bugReport.PriorityId, priority.Select(t => t.Id));
            }

            ViewBag.ProductList = ProductList;
            ViewBag.SeverityList = SeverityList;
            ViewBag.PriorityList = PriorityList;
            ViewBag.StatusList = GetSelectListItemsForRole(bugReport.Assignees, statusEntity, bugReport.StatusId); ;
            //ViewBag.Tags = new SelectList(tagEntity.GetAllTags(), "Id", "Name");

            var viewModel = new EditBugReportViewModel(bugReport);

            return View("/Views/BugReport/EditBugReportUI.cshtml", viewModel);
        }

        // POST: BugReport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditReport(EditBugReportViewModel editBugReportViewModel)
        {
            if (ModelState.IsValid)
            {
                if (bugReportEntity.UpdateBugReport(editBugReportViewModel) == false)
                {
                    throw new Exception("Could not update report.");
                }

                var bugReport = bugReportEntity.GetSingleBugReport(editBugReportViewModel.Id);
                if (bugReport.Subscribers != null &&
                    bugReport.Subscribers.Count > 0)
                {
                    var usersId = bugReport.Subscribers.Select(i => i.UserName).ToList();
                    UserHub.NotifyBugReportChangeToSubscribers(usersId, editBugReportViewModel.Id, editBugReportViewModel.Title, "Update");
                }
                

                return Redirect("/Report/Details/" + editBugReportViewModel.Id);
            }

            var products = productEntity.GetAllProducts();
            var severity = severityEntity.GetAllSeverities();
            var priority = priorityEntity.GetAllPriorities();
            SelectList ProductList;
            SelectList SeverityList;
            SelectList PriorityList;

            if (User.IsInRole("Admin"))
            {
                ProductList = new SelectList(products, "Id", "Name", editBugReportViewModel.ProductId);
                SeverityList = new SelectList(severity, "Id", "Name", editBugReportViewModel.SeverityId);
                PriorityList = new SelectList(priority, "Id", "Name", editBugReportViewModel.PriorityId);
            }
            else
            {
                // Disable editing
                ProductList = new SelectList(products, "Id", "Name", editBugReportViewModel.ProductId, products.Select(t => t.Id));
                SeverityList = new SelectList(severity, "Id", "Name", editBugReportViewModel.SeverityId, severity.Select(t => t.Id));
                PriorityList = new SelectList(priority, "Id", "Name", editBugReportViewModel.PriorityId, priority.Select(t => t.Id));
            }

            ViewBag.ProductList = ProductList;
            ViewBag.SeverityList = SeverityList;
            ViewBag.PriorityList = PriorityList;
            ViewBag.StatusList = GetSelectListItemsForRole(editBugReportViewModel.Assignees, statusEntity, editBugReportViewModel.StatusId); ;


            return View("/Views/BugReport/EditBugReportUI.cshtml", editBugReportViewModel);
        }

        private IEnumerable<SelectListItem> GetSelectListItemsForRole(ICollection<ApplicationUser> assignees, StatusEntity statusEntity, int selectedItem)
        {
            var list = statusEntity.GetAllStatus();
            var selectItem = new List<SelectListItem>();

            foreach (var item in list)
            {
                selectItem.Add(new SelectListItem
                {
                    Value = Convert.ToString(item.Id),
                    Text = item.Name,
                    Selected = (item.Id == selectedItem)
                });
            }
            if (User.IsInRole("Admin"))
            {
                selectItem.First(t => t.Text == "NEW").Disabled = false;
                selectItem.First(t => t.Text == "ASSIGNED").Disabled = false;
                selectItem.First(t => t.Text == "UNVERIFIED_FIXED").Disabled = false;
                selectItem.First(t => t.Text == "VERIFIED_FIXED").Disabled = false;
                selectItem.First(t => t.Text == "INVALID").Disabled = false;
                selectItem.First(t => t.Text == "DUPLICATE").Disabled = false;
            }
            else if (User.IsInRole("Triager"))
            {
                selectItem.First(t => t.Text == "NEW").Disabled = false;
                selectItem.First(t => t.Text == "ASSIGNED").Disabled = false;
                selectItem.First(t => t.Text == "UNVERIFIED_FIXED").Disabled = true;
                selectItem.First(t => t.Text == "VERIFIED_FIXED").Disabled = true;
                selectItem.First(t => t.Text == "INVALID").Disabled = false;
                selectItem.First(t => t.Text == "DUPLICATE").Disabled = false;
            }
            // Only developers assigned to the bug report
            else if (User.IsInRole("Developer") &&
                assignees.FirstOrDefault(i => i.Id == User.Identity.GetUserId()) != null)
            {
                selectItem.First(t => t.Text == "NEW").Disabled = true;
                selectItem.First(t => t.Text == "ASSIGNED").Disabled = true;
                selectItem.First(t => t.Text == "UNVERIFIED_FIXED").Disabled = false;
                selectItem.First(t => t.Text == "VERIFIED_FIXED").Disabled = true;
                selectItem.First(t => t.Text == "INVALID").Disabled = true;
                selectItem.First(t => t.Text == "DUPLICATE").Disabled = true;
            }
            else if (User.IsInRole("Reviewer"))
            {
                selectItem.First(t => t.Text == "NEW").Disabled = true;
                selectItem.First(t => t.Text == "ASSIGNED").Disabled = true;
                selectItem.First(t => t.Text == "UNVERIFIED_FIXED").Disabled = false;
                selectItem.First(t => t.Text == "VERIFIED_FIXED").Disabled = false;
                selectItem.First(t => t.Text == "INVALID").Disabled = true;
                selectItem.First(t => t.Text == "DUPLICATE").Disabled = true;
            }
            else
            {
                foreach (var item in selectItem)
                {
                    item.Disabled = true;
                }
            }

            return selectItem;
        }
    }
}

BugMania/Controllers/BugReport/RemoveSubscriptionBugReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugMania.Entities;
using Microsoft.AspNet.Identity;

namespace BugMania.Controllers.BugReport
{
    [RoutePrefix("Report/Subscribe")]
    public class RemoveSubscriptionBugReportController : Controller
    {
        BugReportEntity bugReportEntity = new BugReportEntity();
        ApplicationUserEntity userEntity = new ApplicationUserEntity();

        // GET: /Report/
        [Route("Remove")]
        public ActionResult RemoveSubscription(int id)
        {
            bugReportEntity.RemoveSubscriber(id, User.Identity.GetUserId());

            return Redirect("/Report/Details/" + id);
        }
    }
}

BugMania/Controllers/BugReport/ViewDetailedBugReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.BugReport
{
    [RoutePrefix("Report")]
    public class ViewDetailedBugReportController : Controller
    {
        private BugReportEntity bugReportEntity = new BugReportEntity();

        [Route("Details/{id}")]
        public ActionResult ViewDetailedReport(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var bugReport = bugReportEntity.GetSingleBugReport(id);
            if (bugReport == null)
            {
                return HttpNotFound();
            }

            DetailsBugReportViewModel detailsModel = new DetailsBugReportViewModel(bugReport);

            return View("/Views/BugReport/ViewDetailedBugReportUI.cshtml", detailsModel);
        }
    }
}

BugMania/Controllers/BugReport/ViewFilteredBugReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.BugReport
{

    [RoutePrefix("Report")]
    public class ViewFilteredBugReportController : Controller
    {
        private BugReportEntity bugReportEntity = new BugReportEntity();
        
        [Route("View")]
        public ActionResult ViewFilteredReports(string filter)
        {
            ViewBag.Filters = filter;
            var model = bugReportEntity.GetFilteredSetOfReports(0, 10, filter);
            return View("/Views/BugReport/ViewBugReportUI.cshtml", model);
        }

        public ActionResult FetchFilteredData(int skipCount, int takeCount, string filter)
        {   
            var model = bugReportEntity.GetFilteredSetOfReports(skipCount, takeCount, filter);

            if (model.Any())
            {
                return PartialView("/Views/BugReport/_ViewBugReportCardUI.cshtml", model);
            }
            else
            {
                return null;
            }
        }
    }
}

BugMania/Views/BugReport/DeleteBugReportUI.cshtml
@model BugMania.Shapes.BugReport

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BugReport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Priority.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Severity.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Severity.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BugMania/Views/BugReport/ViewBugReportUI.cshtml
@model IEnumerable<BugMania.Shapes.BugReport>


@{
    ViewBag.Title = "Home";
}
<div id="report-container" class="div-margin-10">
    <div class="container-fluid">
        <div class="row m-b-10">
            <div class="col-sm-6">
                @Html.ActionLink("+", "CreateReport", "CreateBugReport", null,
                    new { @class = "btn btn-success glyphicon btn-link-text color-white pull-left",
                        Title = "Create Report" })
            </div>
            <div class="col-sm-6">
                @using (Html.BeginForm("ViewFilteredReports", "ViewFilteredBugReport", FormMethod.Get)) {
                    <input type="search" name="filter" class="form-control pull-right searchbox" placeholder="Search" />
                }
            </div>
        </div>
        <div class="min-height-20">
            @if (!String.IsNullOrEmpty(ViewBag.Filters))
            {
                <a class="inline-block card-info search-filter-tag btn-link-text float-right" href="@Url.Action("ViewAllReports", "ViewAllBugReport")">
                    @ViewBag.Filters   <b>x</b>
                </a>
            }
        </div>
    </div>
    <hr />
    <div id="result">
        @Html.Partial("/Views/BugReport/_ViewBugReportCardUI.cshtml")
    </div>
</div>


@section Scripts  {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        // Fetch data when at bottom of scrollbar
        $("#main-content").scroll(function () {
            if ($("#main-content").scrollTop() + $(window).height() >= $("#report-container").height() + $(window).height() * 0.1) {
                
                FetchDataFromServer();
            }
        });

        var skipCount = 10; // start at 11th record (assumes first 10 included in initial view)
        var takeCount = 10; // return new 10 records
        var hasMoreRecords = true;
        var retrievingRecords = false;

        function FetchDataFromServer() {
            
            if (!hasMoreRecords || retrievingRecords) {
                return;
            }
            retrievingRecords = true;

            var filterString = window.location.search.split("=");
            var controllerString = "";
            var actionString = "";
            var data = {};
            // Has filter applied
            if (filterString[0] != "") {
                filterString = filterString[1];
                controllerString = "ViewFilteredBugReport";
                actionString = "FetchFilteredData";
                data = { skipCount: skipCount, takeCount: takeCount, filter: filterString }
            }
            // No filter, get all
            else {
                filterString = filterString[0];
                controllerString = "ViewAllBugReport";
                actionString = "FetchData";
                data = { skipCount: skipCount, takeCount: takeCount }
            }

            $.ajax({
                url: '/' + controllerString + '/' + actionString,
                data: data,
                datatype: 'html',
                success: function (response) {
                    if (response == "") {
                        hasMoreRecords = false;
                    } else {
                        $("#result").append(response);
                        skipCount += takeCount;
                    }
                    retrievingRecords = false;
                },
                error: function () {
                    retrievingRecords = false;
                    alert("Error loading more pages");
                }
            });
        }
    </script>
}

BugMania/Views/BugReport/ViewDetailedBugReportUI.cshtml
@model BugMania.Models.DetailsBugReportViewModel

@using Microsoft.AspNet.Identity
@using BugMania.Helpers;
@using BugMania.Models;
@using BugMania.Helpers;

@{
    ViewBag.Title = Model.Title;
}


<a href="@Request.UrlReferrer.ToString()" class="glyphicon glyphicon-arrow-left btn-link-text font-size-25" title="Back"></a>

<div class="report">
    <div class="report-title">
        @Model.Title
    </div>
    <div class="report-container">
        <div class="report-header">
            <div class="inline-block m-r-5">
                @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "card-info-bold" }):
                @Html.DisplayFor(model => model.Status.Name, new { @class = "" })
            </div>
            <div class="inline-block m-r-5">
                @Html.LabelFor(model => model.Severity, "Severity", htmlAttributes: new { @class = "card-info-bold" }):
                @Html.DisplayFor(model => model.Severity.Name, new { @class = "" })
            </div>
            <div class="inline-block m-r-5">
                @Html.LabelFor(model => model.Priority, "Priority", htmlAttributes: new { @class = "card-info-bold" }):
                @Html.DisplayFor(model => model.Priority.Name, new { @class = "" })
            </div>
            <div class="inline-block m-r-5 float-right">
                @Html.LabelFor(model => model.Assignees, "Assignees", htmlAttributes: new { @class = "card-info-bold" }):
                @if (Model.Assignees.Count() == 0)
                {<span>None</span>}
                @{
                    int count = 1;
                    foreach (var assignee in Model.Assignees)
                    {
                        @Html.DisplayFor(model => assignee.UserName, new { @class = "" })
                        if (count < Model.Assignees.Count)
                        {
                            <span> | </span>
                            count++;
                        }
                    }
                }
            </div>
            <div class="inline-block">
                @Html.LabelFor(model => model.Product, "Product", htmlAttributes: new { @class = "card-info-bold" }):
                @Html.DisplayFor(model => model.Product.Name, new { @class = "" })
            </div>
        </div>
        <hr class="report-header-divider" />
        <div class="report-body">
            @Html.DisplayFor(model => model.Description, new { @class = "" })
        </div>


        <label class="report-footer-post">
            @DateTimeHelpers.GetRelativeTimePassed(Model.CreateDateTime)
            by
            @Html.DisplayFor(model => model.Author.UserName, new { @class = "" })
        </label>
        @if (Model.LastEditDateTime != null)
        {
            <label class="report-footer-edit">
                Edited
                @DateTimeHelpers.getLocalTime(Model.LastEditDateTime)
            </label>
        }

    </div>
    <div class="report-footer2 m-t-10">
        <div>
            @foreach (var tag in Model.Tags)
            {
                <span class="card-info card-tag min-height-40">
                    @Html.DisplayFor((modelItem) => tag.Name)
                </span>
            }
        </div>
        <div>
            @if (Model.Subscribers.Where(i => i.Id == User.Identity.GetUserId()).FirstOrDefault() == null)
            {
                @Html.ActionLink("Subscribe", "AddSubscription", "AddSubscriptionBugReport", new { id = Model.Id }, new { @class = "m-r-5" })
            }
            else
            {
                @Html.ActionLink("Unsubscribe", "RemoveSubscription", "RemoveSubscriptionBugReport", new { id = Model.Id }, new { @class = "m-r-5" })
            }

            @if (User.IsInRole("Admin") ||
                User.IsInRole("Triager"))
            {
                <label>|</label>
                @Html.ActionLink("Edit", "EditReport", "EditBugReport", new { id = Model.Id }, new { @class = "m-r-5" })
                <label>|</label>
                @Html.ActionLink("Delete", "Delete", "DeleteBugReport", new { id = Model.Id }, new { })
            }
            else if (User.IsInRole("Reviewer") ||
            User.IsInRole("Developer"))
            {
                <label>|</label>
                @Html.ActionLink("Edit", "EditReport", "EditBugReport", new { id = Model.Id }, new { })
            }

        </div>
    </div>
</div>



@Html.Partial("/Views/Comment/_CreateCommentUI.cshtml", new CreateCommentViewModel(), new ViewDataDictionary(ViewData)
{
    { "BugReportId", Model.Id }
})


<div class="comments-container">
    @foreach (var comment in Model.getCommentsDescending)
    {
        <div class="comment-card">
            <div class="comment-profile">
                <img class="profile-picture" src="~/Content/Images/default-profile.png" />
                <div class="profile-user">
                    @Html.DisplayFor(model => comment.Commenter.UserName, new { @class = "" })
                </div>
            </div>
            <div class="comment-content">
                <div class="comment-body">
                    @Html.DisplayFor(model => comment.Content, new { @class = "" })
                </div>
                <div class="comment-time">
                    <label>@DateTimeHelpers.GetRelativeTimePassed(comment.CommentDateTime, "Commented")</label>
                </div>
            </div>
        </div>
    }

</div>

BugMania/Views/BugReport/_ViewBugReportCardUI.cshtml
@model IEnumerable<BugMania.Shapes.BugReport>

@using BugMania.Helpers;


@foreach (var item in Model)
{
    <a class="display-block card width-100p min-height-100" href="@Url.Action("ViewDetailedReport", "ViewDetailedBugReport", new { id = item.Id })">

        <div class="card-row">
            <div class="inline-block card-info">
                <label class="btn-link-text">
                    @DateTimeHelpers.GetRelativeTimePassed(item.CreateDateTime)
                </label>
            </div>
            <div class="float-right inline-block">
                <span class="card-label">
                    @Html.DisplayNameFor(model => model.Status.Name):
                </span>
                <span class="card-info">
                    @Html.DisplayFor(modelItem => item.Status.Name)
                </span>
            </div>
        </div>
        <div class="card-row">
            <div class="inline-block card-title">
                <span class="">
                    @item.Title
                </span>
            </div>
            <div class="inline-block float-right">
                <span class="card-label">
                    @Html.DisplayNameFor(model => model.Priority.Name):
                </span>
                <span class="card-info m-r-5">
                    @Html.DisplayFor(modelItem => item.Priority.Name)
                </span>
                <span class="card-label">
                    @Html.DisplayNameFor(model => model.Severity.Name):
                </span>
                <span class="card-info">
                    @Html.DisplayFor(modelItem => item.Severity.Name)
                </span>
            </div>
        </div>
        <div class="card-row bottom-card">
            <div class="inline-block">
                @foreach (var tag in item.Tags)
                {
                    <span class="card-info card-tag">
                        @Html.DisplayFor((a) => tag.Name)
                    </span>
                }
            </div>
            <div class="float-right inline-block">
                <span class="card-label">
                    @Html.DisplayNameFor(model => model.Product.Name):
                </span>
                <span class="card-info">
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </span>
            </div>
        </div>

    </a>
}