BugMania/Controllers/Group/CreateGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using BugMania.Entities;
using BugMania.Models;
using Microsoft.AspNet.Identity;

namespace BugMania.Controllers.Group
{
    [RoutePrefix("Group")]
    [Authorize]
    public class CreateGroupController : Controller
    {
        private GroupEntity groupEntity = new GroupEntity();
        private ProductEntity productEntity = new ProductEntity();
        private ApplicationUserEntity userEntity = new ApplicationUserEntity();

        // GET: Group/Create
        [Route("Create")]
        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(productEntity.GetAllProducts(), "Id", "Name");
            return View("/Views/Group/ViewGroupUI.cshtml", new GroupsViewModel());
        }

        // POST: Group/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GroupsViewModel groupViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = userEntity.GetUserById(HttpContext.User.Identity.GetUserId());
                userEntity.DetachContext(user);

                BugMania.Shapes.Group group = new BugMania.Shapes.Group();
                group.Name = groupViewModel.Name;
                group.ProductId = groupViewModel.ProductId;
                group.GroupMembers.Add(user);
                groupEntity.AddGroup(group);

                return RedirectToAction("View", "ViewGroup");
            }

            return RedirectToAction("View", "ViewGroup");
        }
    }
}

BugMania/Controllers/Group/DeleteGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.Group
{
    public class DeleteGroupController : Controller
    {
        private GroupEntity groupEntity = new GroupEntity();

        // GET: Group/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //BugMania.Shapes.Group group = await db.Groups.FindAsync(id);
            //if (group == null)
            //{
            //    return HttpNotFound();
            //}
            return View();
        }

        // POST: Group/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            return RedirectToAction("Index");
        }
    }
}

BugMania/Controllers/Group/EditGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.Group
{
    public class EditGroupController : Controller
    {
        private GroupEntity groupEntity = new GroupEntity();

        // GET: Group/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //if (group == null)
            //{
            //    return HttpNotFound();
            //}
            //ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", group.ProductId);
            return View();
        }

        // POST: Group/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ProductId")] BugMania.Shapes.Group group)
        {
            if (ModelState.IsValid)
            {
                
                return RedirectToAction("Index");
            }
            //ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", group.ProductId);
            return View(group);
        }
    }
}

BugMania/Controllers/Group/ViewDetailedGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using BugMania.Entities;
using BugMania.Models;
using Microsoft.AspNet.Identity;

namespace BugMania.Controllers.Group
{
    public class ViewDetailedGroupController : Controller
    {
        private GroupEntity groupEntity = new GroupEntity();

        // GET: Group/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //BugMania.Shapes.Group group = await db.Groups.FindAsync(id);
            //if (group == null)
            //{
            //    return HttpNotFound();
            //}
            return View();
        }
    }
}

BugMania/Controllers/Group/ViewGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using BugMania.Models;
using Microsoft.AspNet.Identity;
using BugMania.Entities;

namespace BugMania.Controllers.Group
{
    [RoutePrefix("Group")]
    public class ViewGroupController : Controller
    {
        private ApplicationUserEntity userEntity = new ApplicationUserEntity();
        private ProductEntity productEntity = new ProductEntity();

        // GET: Group
        [Route]
        [Route("View")]
        public ActionResult View()
        {
            var id = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var user = userEntity.GetUserWithGroup(id);
            GroupsViewModel groupsViewModel;
            if (user != null)
            {
                groupsViewModel = new GroupsViewModel(user);
            }
            else
            {
                groupsViewModel = new GroupsViewModel();
            }
            

            ViewBag.ProductId = new SelectList(productEntity.GetAllProducts(), "Id", "Name");
            return View("/Views/Group/ViewGroupUI.cshtml", groupsViewModel);
        }
    }
}

BugMania/Views/Group/DeleteGroupUI.cshtml
@model BugMania.Shapes.Group

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Group</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Product.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Product.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

BugMania/Views/Group/DetailsGroupUI.cshtml
@model BugMania.Shapes.Group

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Group</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Product.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Product.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

BugMania/Views/Group/EditGroupUI.cshtml
@model BugMania.Shapes.Group

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Group</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BugMania/Views/Group/ViewGroupUI.cshtml
@model BugMania.Models.GroupsViewModel

@{

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Your Groups</title>
</head>
<body>
    @if (Model.MemberOf == null || Model.MemberOf.Count == 0)
    {
        <div class="page-placeholder-container">

            <p class="page-placeholder">
                Nothing here yet. Discover groups or Create one.
                <button id="btnShowGroupModal" class="button">+</button>
            </p>
        </div>
    }
    else
    {
        <div class="div-margin-10">
            <div><button id="btnShowGroupModal" class="button m-b-10p">+</button></div>
            <div class="group-view-container">
                @foreach (var item in Model.MemberOf)
                {
                    <a class="btn-link-text">
                        <div class="group-card">
                            <div class="group-content">
                                @item.Name
                            </div>
                        </div>
                    </a>
                }
            </div>
        </div>
    }

</body>
</html>

<div class="modal fade" tabindex="-1" id="createGroupModal"
     data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    ×
                </button>
                <h4 class="modal-title">Create Group</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("/Views/Group/_CreateGroupUI.cshtml")
                <div class="modal-footer">
                    <button type="button" id="btnHideGroupModal" class="btn btn-danger btn-std pull-left">Close</button>
                    <button type="button" id="btnCreateGroup" class="btn btn-info btn-std">Create</button>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#btnShowGroupModal").click(function () {
                $("#createGroupModal").modal('show');
            });
            
            $("#btnHideGroupModal").click(function () {
                $("#createGroupModal").modal('hide');
            });

            // Submit Create Group Form
            $('#btnCreateGroup').click(function () {

                var data = {
                    Name: $("#createGroupName").val(),
                    ProductId: $("#createGroupProduct").val(),
                    __RequestVerificationToken: $('input[name=__RequestVerificationToken]').val()
                };

                $.ajax({
                    type: "post",
                    url: "/CreateGroup/Create",
                    data: data,
                    success: function (response) {
                        $('#createGroupModal').modal('hide');
                        window.location.href = '/Group';
                    },
                    error: function (request, status, error) {
                        alert(request.responseText);
                    }
                })
            });
        });
    </script>
}

BugMania/Views/Group/_CreateGroupUI.cshtml
@model BugMania.Models.GroupsViewModel

@{
    ViewBag.Title = "Create Group";
}

@using (Html.BeginForm("Create", "CreateGroup", FormMethod.Post, new { @id = "createGroupForm" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Name</label>
            <div class="col-md-10">
                <input type="text" id="createGroupName" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Product</label>
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @id = "createGroupProduct", @class = "form-control" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}