BugMania/Controllers/Comment/CreateCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using BugMania.Models;
using BugMania.Entities;
using BugMania.Hubs;
using Microsoft.AspNet.Identity;

namespace BugMania.Controllers.Comment
{
    public class CreateCommentController : Controller
    {
        CommentEntity commentEntity = new CommentEntity();
        BugReportEntity bugReportEntity = new BugReportEntity();

        // GET: Comment/Create
        public ActionResult Create()
        {
            return RedirectToAction("ViewAllReports", "ViewAllBugReport");
        }

        // POST: Comment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCommentViewModel createCommentViewModel)
        {
            if (ModelState.IsValid)
            {
                if (createCommentViewModel.Content.Trim() == "")
                {
                    return Redirect(Request.UrlReferrer.ToString());
                }

                commentEntity.AddComment(createCommentViewModel);

                var bugReport = bugReportEntity.GetSingleBugReport(createCommentViewModel.BugReportId);
                if (bugReport.Subscribers != null &&
                    bugReport.Subscribers.Count > 0)
                {
                    var usersId = bugReport.Subscribers.Select(i => i.UserName).ToList();
                    UserHub.NotifyBugReportChangeToSubscribers(usersId, createCommentViewModel.BugReportId, createCommentViewModel.Content, "Comment");
                }

                return Redirect(Request.UrlReferrer.ToString());
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

BugMania/Controllers/Comment/DeleteCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.Comment
{
    public class DeleteCommentController : Controller
    {
        CommentEntity commentEntity = new CommentEntity();

        // GET: Comment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            return View();
        }

        // POST: Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            commentEntity.DeleteComment(id);
            return RedirectToAction("ViewAllReports", "ViewAllBugReport");
        }
    }
}

BugMania/Controllers/Comment/EditCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.Comment
{
    public class EditCommentController : Controller
    {
        CommentEntity commentEntity = new CommentEntity();

        // GET: Comment/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View();
        }

        // POST: Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BugReportId,Content,CommentDateTime,UserId")] BugMania.Shapes.Comment comment)
        {
            if (ModelState.IsValid)
            {
                commentEntity.UpdateComment(comment);
                return RedirectToAction("ViewAllReports", "ViewAllBugReport");
            }
            return View(comment);
        }
    }
}

BugMania/Controllers/Comment/ViewCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugMania.DataContexts;
using BugMania.Shapes;
using Microsoft.AspNet.Identity;
using BugMania.Models;
using BugMania.Helpers;
using BugMania.Entities;

namespace BugMania.Controllers.Comment
{
    public class ViewCommentController : Controller
    {
        CommentEntity commentEntity = new CommentEntity();
        // GET: Comment
        public ActionResult Index(int id)
        {
            var comments = commentEntity.GetAllComments(id);
            return View(comments);
        }
    }
}

BugMania/Views/Comment/DeleteCommentUI.cshtml
@model BugMania.Shapes.Comment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Comment</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BugReport.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.BugReport.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Commenter.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Commenter.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CommentDateTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CommentDateTime)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

BugMania/Views/Comment/DetailsCommentUI.cshtml
@model BugMania.Shapes.Comment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Comment</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BugReport.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.BugReport.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Commenter.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Commenter.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CommentDateTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CommentDateTime)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

BugMania/Views/Comment/EditCommentUI.cshtml
@model BugMania.Shapes.Comment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Comment</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.BugReportId, "BugReportId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BugReportId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BugReportId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CommentDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CommentDateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CommentDateTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BugMania/Views/Comment/ViewCommentUI.cshtml
@model IEnumerable<BugMania.Shapes.Comment>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BugReport.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Commenter.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CommentDateTime)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BugReport.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Commenter.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CommentDateTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

BugMania/Views/Comment/_CreateCommentUI.cshtml
@model BugMania.Models.CreateCommentViewModel



@using (Html.BeginForm("Create", "CreateComment", FormMethod.Post))
{

    @Html.AntiForgeryToken()

    <div class="create-comment-container">
        <div>
            <input type="hidden" name="BugReportId" id="BugReportId" value=@ViewData["BugReportId"] />

            <textarea rows="4" name="Content" id="Content" class="create-comment-body" placeholder="Leave a comment"></textarea>
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
        <div class="m-t-20">
            <input type="submit" value="Comment" class="btn btn-info btn-std float-right" />
        </div>
    </div>
}